language: java

jdk:
  - openjdk15
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: VoCAwss+cFJRD7LeyC0Y6FUXCCh+Cx4MwxSdYQpgfUdtffhyszVh1e/BDfZvy09ULmHANQV51Rd3h9jWssON3VVLdfFo/g4yGuY2wmnIfnqpfgo2JUsjjn+nQMpVs68HAZffkZiVdjMEn7/z1YLwh7Ewz6+oqWK40Zt4vJuNW/mTjA8r+1HpX65Ouikgl9JWbWr0hsEEUZ3uwcdsvCkfvu+4cck46UEB/SFLNLKfGcG38ofgfb9MOh3OD8tUbpawanOZJfi9FpMvqBO1vLDyI0o257SG37WeWDlGRwhjVopDiYUecwZt0SA5sLIaoARniitEWCFUUaYSvOYoMmR2oM/MQGUvxBXPW2so9GbPxouIrD+jY5Wi3xXuWF1B2c88KlYvymSmb+2QYQA2nPUvpoj1/y6XPfCiO1Q+Kv5o3ICTN9ud4QFsbfsPkJl6VVDdiecAO37ftBYyUiOlRSjMMX3K71Z1tZUCaZ3UHK7EGovRkEIicYhEKImxiFsfqJmIPIEJAs5tIL2WWO6JZM5hvnEJCjPWzGm9lp9drmERyMh6m5aYZhdY/IpMickoa4EfPwoywom6PyP7t1nREV9cjlGedMZs20c30RrRponILFtWn3AueikK3wVpQ06DXbqS3/alk34huaaOq67/eWNjd5889a8bQOvLEL/dpy94/lU=
    - secure: EhxUrcUB4SlZvsyCGEnv20gri9DLBpTDrGXRfrisa3XvZ1ysncSyzs37OIcwHEFSNV5wV5ifrNomtrLu/uAD3L3AegPMkynaE247E1krhroGJdebaA5FlH+tuIPrqqGmRHlOinR8/COCpOlkxOq0+xTwzKkwmMkzAKgMTIx2yh9Rm4vV7zutbgrLXlJbmI/mcbv4B+Z/vZHImCp9fYtkjNROFXZFX8Meg/6s0NJEVGwn+sM0/JdBH2N+SmbPaWDDsE0IIau2+mF6S5rW9xE0W+eeBFt7HC7hDxr2ab2AKBLPdVx4cQA/LfOqIQbPM5vwlcCTQmNXV+cETMfO4xyUVOG3HXRzjHuA+eon5ViN9RFEwGjG5pLl0jPts9dSw7aGSM0EXJCXcKXNlhifZRwomrgaronndUDNJFgD0PmwLnPtckpkHrwSZ8IeMidys51TYEbIvvtVFhjA5FRObLKeKjiF73ofrnMc/9CjTEE6g/gPKOZyLFFW37TBVBaK3x8mxS2rIt/npGUhPkEs2gIOthVrKhUf3IW7aVHrcbCJ7tWjqNJrS9jHfMefYqCZsxZjihp/V7vz4noNGdIl1lF4KELk/NMJETfMnzELryad/k9NcOohdUtRSlK02623fnlApSqIt98lHApDFHpmSWZ8w9ecY7+LEHW+mKNirmAPXVo=
